name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo Building for tag ${{github.ref_name}}

      # https://docs.github.com/en/rest/releases/releases#create-a-release
      # https://docs.github.com/en/rest/releases/assets#upload-a-release-asset
      - name: Create release and upload assets
        run: |
          RELEASE="$(curl \
                       --silent \
                       --show-error \
                       --fail \
                       --request POST \
                       --url https://api.github.com/repos/kgibm/test/releases \
                       --data '{"tag_name":"${{github.ref_name}}"}' \
                       --header "Accept: application/vnd.github.v3+json" \
                       --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq '.id')" && \
          curl \
            --fail \
            --request POST \
            --url https://uploads.github.com/repos/kgibm/test/releases/${RELEASE}/assets?name=README.md \
            --header "Accept: application/vnd.github.v3+json" \
            --header "Content-Type: $(file -b --mime-type README.md)" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --data-binary @README.md
