name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build ${{github.ref_name}},
          echo test, and deploy your project.

      - uses: octokit/request-action@v2.x
        id: create_release
        with:
          route: POST /repos/kgibm/test/releases
          owner: octokit
          repo: request-action
          tag_name: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/kgibm/test/releases/latest
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print details
        run: |
          echo latest release: ${{ fromJson(steps.get_latest_release.outputs.data).id }}
