name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build ${{github.ref_name}},
          echo test, and deploy your project.

      # https://docs.github.com/en/rest/releases/releases#create-a-release
      - uses: octokit/request-action@v2.x
        id: create_release
        with:
          route: POST /repos/kgibm/test/releases
          owner: octokit
          repo: request-action
          tag_name: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/kgibm/test/releases/latest
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print details
        run: |
          echo latest release: ${{ fromJson(steps.get_latest_release.outputs.data).id }}

      # https://docs.github.com/en/rest/releases/assets#upload-a-release-asset
      - name: Add asset
        run: |
          curl \
            --fail-with-body \
            --request POST \
            --url https://uploads.github.com/repos/kgibm/test/releases/latest/assets?name=README.md \
            --header "Accept: application/vnd.github.v3+json" \
            --header "Content-Type: $(file -b --mime-type README.md)" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --data-binary @README.md
